[book]
authors = ["TouriCN"]
language = "zh-CN"
title = "TouriCN"

[output.html]
theme = "theme"
additional-css = ["theme/custom.css"]
additional-js  = ["theme/pagetoc.js"]

[output.html.search]
enable = true
